version = 1

test_patterns = [
  "./..."
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "github.com/quan-to/chevron"

[[analyzers]]
name = "test-coverage"
enabled = true
