dist: xenial

language: go

go:
- 1.10.x

# Only clone the most recent commit.
git:
  depth: 1

before_install:
 - go get github.com/mattn/goveralls



# script always runs to completion (set +e). If we have linter issues AND a
# failing test, we want to see both. Configure golangci-lint with a
# .golangci.yml file at the top level of your repo.
script:
- curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.10.2
- golangci-lint run       # run a bunch of code checkers/linters in parallel
- go test -v -race ./...  # Run all the tests with the race detector enabled
- goveralls -v		  # Run coverage test
