dist: xenial
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - GO111MODULE=on

language: go

go:
- 1.11.x

git:
  depth: 1

before_install:
  - GO111MODULE=off go get github.com/mattn/goveralls
  - echo "deb http://download.rethinkdb.com/apt xenial main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get -qq update && sudo apt-get install -y rethinkdb
  - wget https://releases.hashicorp.com/vault/1.0.2/vault_1.0.2_linux_amd64.zip
  - unzip vault_1.0.2_linux_amd64.zip
  - sudo cp vault /usr/bin
  - cd cmd/agent-ui
  - ./placeholders.sh
  - cd ../..

script:
  - echo "Starting Vault"
  - export VAULT_ADDR='http://127.0.0.1:8200'
  - export VAULT_DEV_ROOT_TOKEN_ID="123456"
  - export VAULT_ROOT_TOKEN=$VAULT_DEV_ROOT_TOKEN_ID
  - export VAULT_ADDRESS="$VAULT_ADDR"
  - export VAULT_USE_USERPASS="true"
  - export VAULT_USERNAME="remotesigner"
  - export VAULT_PASSWORD="123456"
  - export DATABASE_NAME="qrs_test"
  - export DO_START_RETHINK="true"
  - vault server -dev & echo $! > $HOME/vault.pid
  - echo "Waiting vault settle" & sleep 2
  - echo "Vault started with PID `cat $HOME/vault.pid`"
  - vault auth enable userpass
  - vault policy write test-policy ./test-policy.hcl
  - vault write auth/userpass/users/${VAULT_USERNAME} password=${VAULT_PASSWORD} policies=test-policy
  - export
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.15.0
  - golangci-lint run
  - go test -v -race ./... -coverprofile=qrs.coverprofile
  - goveralls -coverprofile=qrs.coverprofile -service travis-ci
  - echo "Closing Vault"
  - sudo kill -9 `cat ~/vault.pid`
  - echo "Calling travis-binary-build.sh"
  - ./travis-binary-build.sh
  - echo "Done"

after_success:
  - mv qrs.coverprofile coverage.txt
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  file_glob: true
  file: zips/*
  skip_cleanup: true
  on:
    tags: true
    repo: quan-to/remote-signer
  api_key:
    secure: Ib/VOdhLDLaUg6CtguRkfy1L5Zrs0y7o0W2z9P3Sxd6KyWnTMdJZqgPBGgwR1ixoFvdaQmtfbyQ0zbZWFigVEts/hzcHmYZsvoRfW6xzMLa46TlDPh0v5xvQ99uOSDiYI9mWOtROPCQym//YZWSu9uzJcRofRtNID7bNwjAEOMiwGENkUP21AgixAc9wKb8mfuIGNWUa+IRRunkqppDkdcmTs+wTdadJAjSnks/4V3nLn2zK1190LS08bOTb3Sj1UhGPgUTTQr8/wESWF2Ni4JYIiy7nItltK3AzHORrQ1MyIQKZkXpdjfuC741kWZX8fHRH+YEY9XK/NPng5tEZXzvOBf7eXZ40gfdaK8E0xWGFm7MbUgK/FN3F098tGcApe97+qIAKyIHevmJMqLNXuN+TI10orPJFeKy5NPZqsMYGuoIW9snVSlGBtSDckaZDysGvKFLiyFSbZyVc05SE9Afx9rJvhr6whERf9Ur8XEcOuGSe6mdrlxSM2/teWU0YjXLLNU5hWVdI+yqXMmd+SdY37XwSNOpzlli3UzkzKSmvqXAMrM6p2m4WkGbXMzxSBCk9yzN9s0ZrgMU5qr1VkrcUTBpoXEiWYQNg3h82XTW/BI3Dg7sUpnptWf5KiRcx7ADTB8mYg0aU29LlcJxIMXCNYVQ2uUB9O9JGqbTnvgE=
